name: Update Feature Flag Status

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [launchdarkly_webhook]

jobs:
  update-feature-flag-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install requests library
        run: pip install requests

      - name: Check feature flag status
        run: |
          flag_status=$(curl -sS https://arnavnad.pythonanywhere.com/)
          if [ "$flag_status" = "enabled" ]; then
            echo "Feature flag is enabled"
            # Trigger GitHub Actions workflow here if needed
          elif [ "$flag_status" = "disabled" ]; then
            echo "Feature flag is disabled"
            # Trigger GitHub Actions workflow here if needed
          else
            echo "Unknown feature flag status"
            exit 1
          fi
