name: Evaluate LaunchDarkly flags
on:
  repository_dispatch:
    types: [flag_updated]  # Listen for webhook events from LaunchDarkly

jobs:
  eval-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate flags
        id: ld
        uses: launchdarkly/gha-flags@v1.0.1
        with:
          sdk-key: ${{ secrets.LAUNCHDARKLY_SDK_KEY }}
          flags: Status_Flag,false
      - name: If true
        if: fromJSON(steps.ld.outputs.Status_Flag) == true
        run: echo "The 'Status_Flag' feature flag is true"
      - name: If false
        if: fromJSON(steps.ld.outputs.Status_Flag) == false
        run: echo "The 'Status_Flag' feature flag is false"

